# list of InnoSetup script to compile
innosetup_scripts:
 - b3-installer-project.iss
 - b3_lite_for_bf3-installer-project.iss

# where to find the InnoSetup compiler
# Courgettes location:
iscc:  C:\Program Files (x86)\Inno Setup 5\ISCC.exe

# where to generate the distribution files
output_dir: ../releases